{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46/comments/48360077.json"}, "html": {"href": "#!/hoffmanlab/genomedata/issues/46#comment-48360077"}}, "issue": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/issues/46.json"}}, "type": "issue", "id": 46, "repository": {"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata.json"}, "html": {"href": "#!/hoffmanlab/genomedata"}, "avatar": {"href": "data/bytebucket.org/ravatar/{78038659-1199-46ff-9d0a-675c62f89d60}ts=python"}}, "type": "repository", "name": "genomedata", "full_name": "hoffmanlab/genomedata", "uuid": "{78038659-1199-46ff-9d0a-675c62f89d60}"}, "title": "Anaconda distribution broken"}, "content": {"raw": "pip install genomedata doesn't work either:\n\n\n```\n#!shell\n(python3) [hpc4366@caclogin02 dev]$ pip install genomedata\nLooking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic\nCollecting genomedata\n  Using cached https://files.pythonhosted.org/packages/ae/a8/095d15019a28d370b0f81a5adb289828dee17b5ac5e069518024526996f6/genomedata-1.4.4.tar.gz\nRequirement already satisfied: numpy in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (1.15.0)\nRequirement already satisfied: tables!=3.4.1,>=3.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (3.4.4)\nRequirement already satisfied: six in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (1.11.0)\nRequirement already satisfied: textinput>=0.2.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (0.2.0)\nRequirement already satisfied: path.py>=11 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from genomedata) (11.5.0)\nRequirement already satisfied: numexpr>=2.5.2 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from tables!=3.4.1,>=3.0->genomedata) (2.6.8)\nRequirement already satisfied: importlib-metadata>=0.5 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages (from path.py>=11->genomedata) (0.6)\nBuilding wheels for collected packages: genomedata\n  Running setup.py bdist_wheel for genomedata ... done\n  Stored in directory: /global/home/hpc4366/.cache/pip/wheels/ca/cf/32/223bb7e516403ed63d3f492870accb7dc54cb601e3f745d3b6\nSuccessfully built genomedata\nInstalling collected packages: genomedata\nSuccessfully installed genomedata-1.4.4\n(python3) [hpc4366@caclogin02 dev]$ genomedata-load --version\nTraceback (most recent call last):\n  File \"/global/home/hpc4366/.conda/envs/python3/bin/genomedata-load\", line 7, in <module>\n    from genomedata.load_genomedata import main\n  File \"/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/genomedata/__init__.py\", line 28, in <module>\n    import tables\n  File \"/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/tables/__init__.py\", line 93, in <module>\n    from .utilsextension import (\nImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-5.4.0/lib64/libstdc++.so.6)\n\n```\n\n(I switched to python 3 here but python 2 fails as well with an even more cryptic error)", "markup": "markdown", "html": "<p>pip install genomedata doesn't work either:</p>\n<div class=\"codehilite language-shell\"><pre><span></span><span class=\"o\">(</span>python3<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 dev<span class=\"o\">]</span>$ pip install genomedata\nLooking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic\nCollecting genomedata\n  Using cached https://files.pythonhosted.org/packages/ae/a8/095d15019a28d370b0f81a5adb289828dee17b5ac5e069518024526996f6/genomedata-1.4.4.tar.gz\nRequirement already satisfied: numpy in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">1</span>.15.0<span class=\"o\">)</span>\nRequirement already satisfied: tables!<span class=\"o\">=</span><span class=\"m\">3</span>.4.1,&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">3</span>.4.4<span class=\"o\">)</span>\nRequirement already satisfied: six in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">1</span>.11.0<span class=\"o\">)</span>\nRequirement already satisfied: textinput&gt;<span class=\"o\">=</span><span class=\"m\">0</span>.2.0 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">0</span>.2.0<span class=\"o\">)</span>\nRequirement already satisfied: path.py&gt;<span class=\"o\">=</span><span class=\"m\">11</span> in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">11</span>.5.0<span class=\"o\">)</span>\nRequirement already satisfied: numexpr&gt;<span class=\"o\">=</span><span class=\"m\">2</span>.5.2 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from tables!<span class=\"o\">=</span><span class=\"m\">3</span>.4.1,&gt;<span class=\"o\">=</span><span class=\"m\">3</span>.0-&gt;genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">2</span>.6.8<span class=\"o\">)</span>\nRequirement already satisfied: importlib-metadata&gt;<span class=\"o\">=</span><span class=\"m\">0</span>.5 in /global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages <span class=\"o\">(</span>from path.py&gt;<span class=\"o\">=</span><span class=\"m\">11</span>-&gt;genomedata<span class=\"o\">)</span> <span class=\"o\">(</span><span class=\"m\">0</span>.6<span class=\"o\">)</span>\nBuilding wheels <span class=\"k\">for</span> collected packages: genomedata\n  Running setup.py bdist_wheel <span class=\"k\">for</span> genomedata ... <span class=\"k\">done</span>\n  Stored in directory: /global/home/hpc4366/.cache/pip/wheels/ca/cf/32/223bb7e516403ed63d3f492870accb7dc54cb601e3f745d3b6\nSuccessfully built genomedata\nInstalling collected packages: genomedata\nSuccessfully installed genomedata-1.4.4\n<span class=\"o\">(</span>python3<span class=\"o\">)</span> <span class=\"o\">[</span>hpc4366@caclogin02 dev<span class=\"o\">]</span>$ genomedata-load --version\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/bin/genomedata-load&quot;</span>, line <span class=\"m\">7</span>, in &lt;module&gt;\n    from genomedata.load_genomedata import main\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/genomedata/__init__.py&quot;</span>, line <span class=\"m\">28</span>, in &lt;module&gt;\n    import tables\n  File <span class=\"s2\">&quot;/global/home/hpc4366/.conda/envs/python3/lib/python3.6/site-packages/tables/__init__.py&quot;</span>, line <span class=\"m\">93</span>, in &lt;module&gt;\n    from .utilsextension import <span class=\"o\">(</span>\nImportError: /lib64/libc.so.6: version <span class=\"sb\">`</span>GLIBC_2.18<span class=\"err\">&#39;</span> not found <span class=\"o\">(</span>required by /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/gcc-5.4.0/lib64/libstdc++.so.6<span class=\"o\">)</span>\n</pre></div>\n\n\n<p>(I switched to python 3 here but python 2 fails as well with an even more cryptic error)</p>", "type": "rendered"}, "created_on": "2018-10-15T18:40:15.905474+00:00", "user": {"display_name": "Kate Cook", "uuid": "{36c88b70-42d6-4662-bde3-2316c4423895}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D"}, "html": {"href": "https://bitbucket.org/%7B36c88b70-42d6-4662-bde3-2316c4423895%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f46c0bafb4d227957572a7f47c9e2980d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsKC-4.png"}}, "nickname": "katecook", "type": "user", "account_id": "557058:499caa63-3f6a-4f40-b404-8fc921427fc9"}, "updated_on": null, "type": "issue_comment", "id": 48360077}