{"links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/11/comments/10169985.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/11/_/diff#comment-10169985"}}, "parent": {"id": 10168448, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/11/comments/10168448.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/11/_/diff#comment-10168448"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 11, "links": {"self": {"href": "data/repositories/hoffmanlab/genomedata/pullrequests/11.json"}, "html": {"href": "#!/hoffmanlab/genomedata/pull-requests/11"}}, "title": "Py3 compat"}, "content": {"raw": "> I'm proposing not importing anything from future_builtins at all.\n\nSounds great to me.\n\nAs far as packaging is concerned, going forward setuptools is the way to go. There really should be no reference to ez_setup since it can cause issues if the module is not installed. It was used as a bootstrap to make sure setuptools is installed but technically now there's the module 'ensurepip' available in 2.7.9 and all newer versions of 3.5+.\n\nI think you just take out the ez_setup import (along with use_setuptools) without issue. I haven't tested this though.\n\nAs far as the unicode decoding error is concerned it's probably an issue with the version of setuptools you have installed. This was really common with our numpy installation testing. I think upgrading your version of setuptools should fix the issue.\n\nFor reference here's the guidelines we're following regarding python packaging:\nhttps://packaging.python.org/en/latest/distributing/", "markup": "markdown", "html": "<blockquote>\n<p>I'm proposing not importing anything from future_builtins at all.</p>\n</blockquote>\n<p>Sounds great to me.</p>\n<p>As far as packaging is concerned, going forward setuptools is the way to go. There really should be no reference to ez_setup since it can cause issues if the module is not installed. It was used as a bootstrap to make sure setuptools is installed but technically now there's the module 'ensurepip' available in 2.7.9 and all newer versions of 3.5+.</p>\n<p>I think you just take out the ez_setup import (along with use_setuptools) without issue. I haven't tested this though.</p>\n<p>As far as the unicode decoding error is concerned it's probably an issue with the version of setuptools you have installed. This was really common with our numpy installation testing. I think upgrading your version of setuptools should fix the issue.</p>\n<p>For reference here's the guidelines we're following regarding python packaging:\n<a href=\"https://packaging.python.org/en/latest/distributing/\" rel=\"nofollow\" class=\"ap-connect-link\">https://packaging.python.org/en/latest/distributing/</a></p>", "type": "rendered"}, "created_on": "2015-09-23T14:48:03.251356+00:00", "user": {"display_name": "Eric Roberts", "uuid": "{cd8c1fe0-28ca-45fb-8ef9-48090b42bb80}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D"}, "html": {"href": "https://bitbucket.org/%7Bcd8c1fe0-28ca-45fb-8ef9-48090b42bb80%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17548d71dfb29d015b880f48cfc01ca3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsER-5.png"}}, "nickname": "ericr86", "type": "user", "account_id": "557058:c80ca578-03a1-4ac6-b3ee-50372a3fceee"}, "updated_on": "2015-09-23T14:59:23.351431+00:00", "type": "pullrequest_comment", "id": 10169985}